services:
  backend:
    build: 
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    container_name: express_backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/srv/backend
      - /srv/backend/node_modules
      - vscode-server:/root/.vscode-server
      - ${SSH_AUTH_SOCK}:/ssh-agent:/ssh-agent
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - SSH_AUTH_SOCK=/ssh-agent

  frontend:
    build: 
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/srv/frontend
      - /srv/frontend/node_modules
      - vscode-server:/root/.vscode-server
      - ${SSH_AUTH_SOCK}:/ssh-agent:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.28
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  # vscode-extensions:
  vscode-server: